# Generated by Django 3.2.9 on 2021-12-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profession', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('middle_name', models.CharField(max_length=300, null=True)),
                ('professions', models.ManyToManyField(related_name='persons', to='profession.Profession')),
            ],
        ),
    ]
