# Generated by Django 4.0 on 2021-12-13 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('film', '0005_remove_film_actors_remove_film_genre_film_finance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1500)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='film.film')),
            ],
        ),
    ]
