# Generated by Django 3.2.9 on 2021-12-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('production_year', models.DateField()),
                ('preview_picture', models.ImageField(upload_to='')),
                ('slogan', models.CharField(max_length=200)),
                ('duration', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
