# Generated by Django 3.2.9 on 2021-12-08 13:13

from django.db import migrations, models
import film.models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0001_initial'),
        ('country', '0001_initial'),
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='country',
            field=models.ManyToManyField(related_name='films', to='country.Country'),
        ),
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.ManyToManyField(related_name='films', to='genre.Genre'),
        ),
        migrations.AlterField(
            model_name='film',
            name='preview_picture',
            field=models.ImageField(upload_to=film.models.film_directory_path),
        ),
    ]
