# Generated by Django 3.2.9 on 2021-12-10 14:09

from django.db import migrations, models
import film.models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_auto_20211208_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='preview_picture',
            field=models.ImageField(null=True, upload_to=film.models.film_directory_path),
        ),
    ]
