# Generated by Django 3.2.9 on 2021-12-10 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0001_initial'),
        ('film', '0003_alter_film_preview_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='films', to='human.human'),
        ),
    ]
