# Generated by Django 4.0 on 2021-12-13 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('film', '0004_film_actors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='film',
            name='genre',
        ),
        migrations.AddField(
            model_name='film',
            name='finance',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='film', to='finance.finance'),
        ),
    ]
