# Generated by Django 4.0 on 2021-12-13 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0005_remove_film_actors_remove_film_genre_film_finance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='country',
            new_name='countries',
        ),
    ]
